[package]
name = "risc16_rs"
version = "0.1.0"
authors = ["Ken <ken@kenh.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
lazy_static = "1.4.0"
